#!/usr/bin/env bash
# @file add_part_of_label
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

PODS=$(kubectl -n nb get pods| grep name- | awk '{print $1}')

## Make sure pods have part-of label applied
## Used for association of pods to a TMC Application
for pod in $PODS; do
    kubectl label -n nb --overwrite pod/"$pod" app.kubernetes.io/part-of=alb-development-apps
done