kind: Namespace
apiVersion: v1
metadata:
  name: name-brainstormulator
  labels:
    name: name-brainstormulator
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: name-brainstormulator
  namespace: name-brainstormulator
  labels:
    app: name-brainstormulator
spec:
  replicas: 10
  selector:
    matchLabels:
      app: name-brainstormulator
  template:
    metadata:
      labels:
        app: name-brainstormulator
    spec:
      containers:
      - name: name-brainstormulator
        image: ali5ter/name-brainstormulator:1.0
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: name-brainstormulator
spec:
  selector:
    app: name-brainstormulator
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080