# 
# @file deployment.yaml
# Deploy name-brainstormulator web app within a namespace access it with
# a service
#
---
kind: Namespace
apiVersion: v1
metadata:
  name: nb
  labels:
    name: name-brainstormulator
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: name-brainstormulator
  namespace: nb
  labels:
    app: name-brainstormulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: name-brainstormulator
  template:
    metadata:
      labels:
        app: name-brainstormulator
    spec:
      containers:
      - name: name-brainstormulator
        image: ali5ter/name-brainstormulator:1.2
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: name-brainstormulator
  namespace: nb
spec:
  selector:
    app: name-brainstormulator
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80