# 
# @file deployment.yaml
# Deploy name-brainstormulator web app within a namespace access it with
# a service
#
---
kind: Namespace
apiVersion: v1
metadata:
  name: nb
  labels:
    name: name-brainstormulator
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: name-brainstormulator
  namespace: nb
  labels:
    app: name-brainstormulator
spec:
  replicas: 5
  selector:
    matchLabels:
      app: name-brainstormulator
  template:
    metadata:
      labels:
        app: name-brainstormulator
        app.kubernetes.io/part-of: alb-development-apps
    spec:
      containers:
      - name: name-brainstormulator
        image: ali5ter/name-brainstormulator:1.3
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  # labels:
  #   app: name-brainstormulator
  name: name-brainstormulator
  namespace: nb
spec:
  # type: ClusterIP
  # sessionAffinity: None
  selector:
    app: name-brainstormulator
  ports:
    - port: 8080
      targetPort: 80