# 
# @file deployment_kind.yaml
# Deploy name-brainstormulator web app within a namespace access it with
# a service
#
---
kind: Namespace
apiVersion: v1
metadata:
  name: nb
  labels:
    name: name-brainstormulator
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: name-brainstormulator
  namespace: nb
  labels:
    app: name-brainstormulator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: name-brainstormulator
  template:
    metadata:
      labels:
        app: name-brainstormulator
    spec:
      containers:
      - name: name-brainstormulator
        image: ali5ter/name-brainstormulator:1.3
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: name-brainstormulator
  namespace: nb
spec:
  # Use cloud-provider-kind to expose the service
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: name-brainstormulator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080