# 
# @file kind-config.yaml
# Kind cluster configuration
# @ref https://kind.sigs.k8s.io/docs/user/configuration/
#
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: alb-dev-local
nodes:
- role: control-plane
- role: worker
- role: worker