#!/usr/bin/env bash
# @file start_kind_cluster
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

# Assumes kind is installed (brew install kind)
# Assumes cloud-provider-kind is installed (brew install cloud-provider-kind)

kind create cluster --config kind-config.yaml

# Start the cloud-provider-kind in a separate terminal
# sudo cloud-provider-kind

kubctl apply -f ./deployment_kind.yaml

# Find the external IP to connect to

kubectl get services -A