#!/usr/bin/env bash
# @file start_kind_cluster
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>
# Prereqs:
# kind is installed (brew install kind)
# cloud-provider-kind is installed (brew install cloud-provider-kind)

# Create the kind cluster
kind create cluster --config kind-config.yaml

# Start the cloud-provider-kind in a separate terminal
sudo cloud-provider-kind &

# Deploy the app
kubectl apply -f deployment-kind.yaml

# Find the external IP to use in a URL to access the app
kubectl get services -n nb