kind: Deployment
apiVersion: apps/v1
metadata:
  name: name-brainstormulator
  namespace: nb
  labels:
    app: name-brainstormulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: name-brainstormulator
  template:
    metadata:
      labels:
        app: name-brainstormulator
    spec:
      containers:
      - name: name-brainstormulator
        image: ali5ter/name-brainstormulator:1.3
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5