kind: Service
apiVersion: v1
metadata:
  # labels:
  #   app: name-brainstormulator
  name: name-brainstormulator
  namespace: nb
spec:
  # type: ClusterIP
  # sessionAffinity: None
  selector:
    app: name-brainstormulator
  ports:
    - port: 8080
      targetPort: 80